# Generated by Django 6.0.5 on 2026-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleitor',
            name='cpf',
            field=models.CharField(help_text='000.000.000-00', max_length=14, unique=True),
        ),
    ]
